name: Build
run-name: Build repository
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false
      - run: git config --global init.defaultBranch main
      - run: gem install rails
      - run: cd\
      - run: rails new remote
      - run: git commit -m"[Run Build]"
      - run: bin/rails server
