name: Build
run-name: Build repository
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - run: gem install rails
      - run: cd remote
      - run: bin/rails server
