name: Build
run-name: Build repository
on: [push]
jobs:
  good:
    name: djss
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby environment with ruby-build
        uses: clupprich/ruby-build-action@v1.3.0
        with:
          ruby-version: 2.6.5
          cache-available: false
  import_checkout:
    name: Import Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Install Checkout
  import_ruby:
    name: Import Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        name: Install Ruby
        with:
          ruby-version: '3.0'
          bundler-cache: false
  build_project:
   name: Build project
   runs-on: ubuntu-latest
   needs: [import_checkout, import_ruby]
   steps:
     - run: |
          echo "::group::Print Build Version"
          echo "build@v1"
          echo "::endgroup::"
       name: Build
